### ISSUE TITLE
small bug

### ISSUE THREAD

**Issue by Sle0999** [Gyarbij/Plexist#35]
this is the error im getting after running this in docker. Error doesnt always happen and usually happens after the script has been running for a while.

btw, your script is awesome, thanks for the work!

INFO:root:retrying search for Revenons à nos moutons
INFO:root:search for Revenons à nos moutons successful
INFO:root:retrying search for Der Vogel auf dem Felsen
INFO:root:search for Der Vogel auf dem Felsen successful
INFO:root:Updated playlist Intense Studying - SSpotify
INFO:root:Updated playlist Intense Studying - SSpotify with summary and poster
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/spotipy/oauth2.py", line 265, in _request_access_token
    response.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Timeout for url: https://accounts.spotify.com/api/token
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/plexist/plexist.py", line 135, in <module>
    main()
  File "/app/plexist/plexist.py", line 117, in main
    spotify_playlist_sync(sp, plex, user_inputs)
  File "/app/plexist/modules/spotify.py", line 77, in spotify_playlist_sync
    tracks = _get_sp_tracks_from_playlist(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/plexist/modules/spotify.py", line 49, in _get_sp_tracks_from_playlist
    sp_playlist_tracks = sp.user_playlist_tracks(user_id, playlist.id)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/spotipy/client.py", line 781, in user_playlist_tracks
    return self.playlist_tracks(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/spotipy/client.py", line 683, in playlist_tracks
    return self.playlist_items(playlist_id, fields, limit, offset,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/spotipy/client.py", line 707, in playlist_items
    return self._get(
           ^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/spotipy/client.py", line 323, in _get
    return self._internal_call("GET", url, payload, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/spotipy/client.py", line 247, in _internal_call
    headers = self._auth_headers()
              ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/spotipy/client.py", line 238, in _auth_headers
    token = self.auth_manager.get_access_token(as_dict=False)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/spotipy/oauth2.py", line 238, in get_access_token
    token_info = self._request_access_token()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/spotipy/oauth2.py", line 269, in _request_access_token
    self._handle_oauth_error(http_error)
  File "/usr/local/lib/python3.12/site-packages/spotipy/oauth2.py", line 146, in _handle_oauth_error
    raise SpotifyOauthError(
spotipy.oauth2.SpotifyOauthError: error: upstream request timeout, error_description: None

**Comment by Gyarbij** [comment]
I'll take a look at it today, but if you can try to Dev build and let me know if it's occurring there as well. There are a few changes so take a look at the commit messages.

**Comment by Gyarbij** [comment]
@Sle0999 can you try the latest or test tags to see if it resolves the issues? If not can you post the latest error. Thanks

**Comment by Sle0999** [comment]
that errors seems to be resolved. Im getting another error now however im unsure if its the script of my plex host, im troubleshooting now. Thanks by the way!


During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/plexist/plexist.py", line 136, in <module>
    main()
  File "/app/plexist/plexist.py", line 118, in main
    spotify_playlist_sync(sp, plex, user_inputs)
  File "/app/plexist/modules/spotify.py", line 81, in spotify_playlist_sync
    update_or_create_plex_playlist(plex, playlist, tracks, userInputs)
  File "/app/plexist/modules/plex.py", line 139, in update_or_create_plex_playlist
    available_tracks, missing_tracks = _get_available_plex_tracks(plex, tracks)  
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/plexist/modules/plex.py", line 77, in _get_available_plex_tracks
    results = list(executor.map(lambda track: _match_single_track(plex, track), tracks))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 619, in result_iterator
    yield _result_or_cancel(fs.pop())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 317, in _result_or_cancel
    return fut.result(timeout)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/plexist/modules/plex.py", line 77, in <lambda>
    results = list(executor.map(lambda track: _match_single_track(plex, track), tracks))
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/plexist/modules/plex.py", line 95, in _match_single_track
    search = plex.search(search_query, mediatype="track", limit=5)  
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/plexapi/server.py", line 803, in search
    for hub in self.fetchItems(key, Hub):
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/plexapi/base.py", line 255, in fetchItems
    data = self._server.query(ekey, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/plexapi/server.py", line 759, in query
    response = method(url, headers=headers, timeout=timeout, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='192.168.1.118', port=32400): Read timed out.

**Comment by Sle0999** [comment]
all good, i think it was the server, i switched to another server and no more error.
