### ISSUE TITLE
SQL ERROR

### ISSUE THREAD

**Issue by technikly** [Gyarbij/Plexist#38]
**Describe the bug**
Unable to sync due to error message.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to run program for the first time.
2. See error

I'm running the latest version with SQL

Error:

(myenv) tom@debian:~/plex-playlist-sync/Plexist$ docker logs plexist
INFO:root:Starting playlist sync
INFO:root:Starting Spotify playlist sync
INFO:root:Syncing playlist: 2023-10 October
Traceback (most recent call last):
  File "/app/plexist/plexist.py", line 102, in <module>
    main()
  File "/app/plexist/plexist.py", line 84, in main
    spotify_playlist_sync(sp, plex, user_inputs)
  File "/app/plexist/modules/spotify.py", line 83, in spotify_playlist_sync
    update_or_create_plex_playlist(plex, playlist, tracks, userInputs)
  File "/app/plexist/modules/plex.py", line 149, in update_or_create_plex_playlist
    available_tracks, missing_tracks = _get_available_plex_tracks(plex, tracks)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/plexist/modules/plex.py", line 81, in _get_available_plex_tracks
    results = list(executor.map(lambda track: _match_single_track(plex, track), tracks))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 619, in result_iterator
    yield _result_or_cancel(fs.pop())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 317, in _result_or_cancel
    return fut.result(timeout)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/plexist/modules/plex.py", line 81, in <lambda>
    results = list(executor.map(lambda track: _match_single_track(plex, track), tracks))
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/plexist/modules/plex.py", line 92, in _match_single_track
    plex_id = get_matched_song(track.title, track.artist, track.album)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/plexist/modules/plex.py", line 45, in get_matched_song
    cursor = conn.cursor()
             ^^^^^^^^^^^^^
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 139969673276288 and this is thread id 139969645176512.
INFO:root:Starting playlist sync
INFO:root:Starting Spotify playlist sync
INFO:root:Syncing playlist: 2023-10 October
Traceback (most recent call last):
  File "/app/plexist/plexist.py", line 102, in <module>
    main()
  File "/app/plexist/plexist.py", line 84, in main
    spotify_playlist_sync(sp, plex, user_inputs)
  File "/app/plexist/modules/spotify.py", line 83, in spotify_playlist_sync
    update_or_create_plex_playlist(plex, playlist, tracks, userInputs)
  File "/app/plexist/modules/plex.py", line 149, in update_or_create_plex_playlist
    available_tracks, missing_tracks = _get_available_plex_tracks(plex, tracks)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/plexist/modules/plex.py", line 81, in _get_available_plex_tracks
    results = list(executor.map(lambda track: _match_single_track(plex, track), tracks))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 619, in result_iterator
    yield _result_or_cancel(fs.pop())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 317, in _result_or_cancel
    return fut.result(timeout)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/plexist/modules/plex.py", line 81, in <lambda>
    results = list(executor.map(lambda track: _match_single_track(plex, track), tracks))
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/plexist/modules/plex.py", line 92, in _match_single_track
    plex_id = get_matched_song(track.title, track.artist, track.album)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/plexist/modules/plex.py", line 45, in get_matched_song
    cursor = conn.cursor()
             ^^^^^^^^^^^^^
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140547889957760 and this is thread id 140547861857984.
INFO:root:Starting playlist sync
INFO:root:Starting Spotify playlist sync
INFO:root:Syncing playlist: 2023-10 October
Traceback (most recent call last):
  File "/app/plexist/plexist.py", line 102, in <module>
    main()
  File "/app/plexist/plexist.py", line 84, in main
    spotify_playlist_sync(sp, plex, user_inputs)
  File "/app/plexist/modules/spotify.py", line 83, in spotify_playlist_sync
    update_or_create_plex_playlist(plex, playlist, tracks, userInputs)
  File "/app/plexist/modules/plex.py", line 149, in update_or_create_plex_playlist
    available_tracks, missing_tracks = _get_available_plex_tracks(plex, tracks)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/plexist/modules/plex.py", line 81, in _get_available_plex_tracks
    results = list(executor.map(lambda track: _match_single_track(plex, track), tracks))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 619, in result_iterator
    yield _result_or_cancel(fs.pop())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 317, in _result_or_cancel
    return fut.result(timeout)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/plexist/modules/plex.py", line 81, in <lambda>
    results = list(executor.map(lambda track: _match_single_track(plex, track), tracks))
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/plexist/modules/plex.py", line 92, in _match_single_track
    plex_id = get_matched_song(track.title, track.artist, track.album)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/plexist/modules/plex.py", line 45, in get_matched_song
    cursor = conn.cursor()
             ^^^^^^^^^^^^^
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140054347602816 and this is thread id 140054319511232.
INFO:root:Starting playlist sync
INFO:root:Starting Spotify playlist sync
INFO:root:Syncing playlist: 2023-10 October
Traceback (most recent call last):
  File "/app/plexist/plexist.py", line 102, in <module>
    main()
  File "/app/plexist/plexist.py", line 84, in main
    spotify_playlist_sync(sp, plex, user_inputs)
  File "/app/plexist/modules/spotify.py", line 83, in spotify_playlist_sync
    update_or_create_plex_playlist(plex, playlist, tracks, userInputs)
  File "/app/plexist/modules/plex.py", line 149, in update_or_create_plex_playlist
    available_tracks, missing_tracks = _get_available_plex_tracks(plex, tracks)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/plexist/modules/plex.py", line 81, in _get_available_plex_tracks
    results = list(executor.map(lambda track: _match_single_track(plex, track), tracks))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 619, in result_iterator
    yield _result_or_cancel(fs.pop())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 317, in _result_or_cancel
    return fut.result(timeout)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/plexist/modules/plex.py", line 81, in <lambda>
    results = list(executor.map(lambda track: _match_single_track(plex, track), tracks))
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/plexist/modules/plex.py", line 92, in _match_single_track
    plex_id = get_matched_song(track.title, track.artist, track.album)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/plexist/modules/plex.py", line 45, in get_matched_song
    cursor = conn.cursor()
             ^^^^^^^^^^^^^
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 139988585884544 and this is thread id 139988557784768.
INFO:root:Starting playlist sync
INFO:root:Starting Spotify playlist sync
INFO:root:Syncing playlist: 2023-10 October
Traceback (most recent call last):
  File "/app/plexist/plexist.py", line 102, in <module>
    main()
  File "/app/plexist/plexist.py", line 84, in main
    spotify_playlist_sync(sp, plex, user_inputs)
  File "/app/plexist/modules/spotify.py", line 83, in spotify_playlist_sync
    update_or_create_plex_playlist(plex, playlist, tracks, userInputs)
  File "/app/plexist/modules/plex.py", line 149, in update_or_create_plex_playlist
    available_tracks, missing_tracks = _get_available_plex_tracks(plex, tracks)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/plexist/modules/plex.py", line 81, in _get_available_plex_tracks
    results = list(executor.map(lambda track: _match_single_track(plex, track), tracks))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 619, in result_iterator
    yield _result_or_cancel(fs.pop())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 317, in _result_or_cancel
    return fut.result(timeout)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/plexist/modules/plex.py", line 81, in <lambda>
    results = list(executor.map(lambda track: _match_single_track(plex, track), tracks))
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/plexist/modules/plex.py", line 92, in _match_single_track
    plex_id = get_matched_song(track.title, track.artist, track.album)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/plexist/modules/plex.py", line 45, in get_matched_song
    cursor = conn.cursor()
             ^^^^^^^^^^^^^
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140378082790272 and this is thread id 140378054690496.
INFO:root:Starting playlist sync
INFO:root:Starting Spotify playlist sync
INFO:root:Syncing playlist: 2023-10 October
Traceback (most recent call last):
  File "/app/plexist/plexist.py", line 102, in <module>
    main()
  File "/app/plexist/plexist.py", line 84, in main
    spotify_playlist_sync(sp, plex, user_inputs)
  File "/app/plexist/modules/spotify.py", line 83, in spotify_playlist_sync
    update_or_create_plex_playlist(plex, playlist, tracks, userInputs)
  File "/app/plexist/modules/plex.py", line 149, in update_or_create_plex_playlist
    available_tracks, missing_tracks = _get_available_plex_tracks(plex, tracks)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/plexist/modules/plex.py", line 81, in _get_available_plex_tracks
    results = list(executor.map(lambda track: _match_single_track(plex, track), tracks))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 619, in result_iterator
    yield _result_or_cancel(fs.pop())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 317, in _result_or_cancel
    return fut.result(timeout)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/plexist/modules/plex.py", line 81, in <lambda>
    results = list(executor.map(lambda track: _match_single_track(plex, track), tracks))
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/plexist/modules/plex.py", line 92, in _match_single_track
    plex_id = get_matched_song(track.title, track.artist, track.album)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/plexist/modules/plex.py", line 45, in get_matched_song
    cursor = conn.cursor()
             ^^^^^^^^^^^^^
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 139739639626624 and this is thread id 139739611535040.
(myenv) tom@debian:~/plex-playlist-sync/Plexist$

**Comment by technikly** [comment]
I've tried using v. 2.0.8 but now I get this error
    plex_playlist.removeItems(plex_playlist.items())
  File "/usr/local/lib/python3.12/site-packages/plexapi/playlist.py", line 243, in removeItems
    raise BadRequest('Cannot remove items from a smart playlist.')
plexapi.exceptions.BadRequest: Cannot remove items from a smart playlist.
(myenv) tom@debian:~/plex-playlist-sync/Plexist/Plexist$

**Comment by technikly** [comment]
def _update_plex_playlist(
    plex: PlexServer,
    available_tracks: List,
    playlist: Playlist,
    append: bool = False,
) -> plexapi.playlist.Playlist:
    try:
        plex_playlist = plex.playlist(playlist.name)
        if not append:
            plex_playlist.removeItems(plex_playlist.items())
        plex_playlist.addItems(available_tracks)
        return plex_playlist
    except BadRequest as e:
        logging.warning(f"Failed to update playlist {playlist.name}: {str(e)}")
        return None  # return None or handle it accordingly


Ungraceful solution.

**Comment by Gyarbij** [comment]
Hi, I'll look into it this week and fix it.

**Comment by Mikec78660** [comment]
Getting the same error with both latest and dev.

sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 139865355811712 and this is thread id 139865320761024.

**Comment by Gyarbij** [comment]
Can you try the latest dev @Mikec78660 @technikly 

If you're using docker:
`docker pull gyarbij/plexist:dev`

**Comment by Mikec78660** [comment]
Not getting an error now but all I get int he output is this:

NFO:root:Starting playlist sync
INFO:root:Starting Spotify playlist sync
INFO:root:Syncing playlist: My Playlist #7
INFO:root:Starting playlist sync
INFO:root:Starting Spotify playlist sync

It hung on "INFO:root:Syncing playlist: My Playlist #7" so I restarted the container and it didn't seem to even get as far the second time. That was using the dev image.

**Comment by Gyarbij** [comment]
@Mikec78660 I'm testing with Deezer, would have to look into to spotify.

**Comment by Mikec78660** [comment]
ok so after about 10 minutes I got a 404 error on spotify. It wanted me to verify my email address again for some reason. But after doing that I am getting this error:

Traceback (most recent call last):
  File "/app/plexist/plexist.py", line 102, in <module>
    main()
  File "/app/plexist/plexist.py", line 84, in main
    spotify_playlist_sync(sp, plex, user_inputs)
  File "/app/plexist/modules/spotify.py", line 79, in spotify_playlist_sync
    tracks = _get_sp_tracks_from_playlist(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/plexist/modules/spotify.py", line 51, in _get_sp_tracks_from_playlist
    tracks = list(
             ^^^^^
  File "/app/plexist/modules/spotify.py", line 47, in extract_sp_track_metadata
    return Track(title, artist, album, url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Track.__init__() missing 2 required positional arguments: 'year' and 'genre'

This is using spotify and using plexist in portainer.

**Comment by Gyarbij** [comment]
Thanks for the details, I see the error as i fixed it for Deezer. Its due to the improved matching using more parameters. Ill check the spotify api to see if they also provide that info in the same format, if not I'll set those to optional.

**Comment by Gyarbij** [comment]
Pushed an update to dev that should hopefully address the spotify issue. If any errors let me know and i'll dust off my spotify account this weekend and do some more detailed fixing.

**Comment by Mikec78660** [comment]
Thank you for addressing this so quickly!

Just tried it and looks like maybe just a format issue in one of the python scripts?

IndentationError: expected an indented block after function definition on line 42
Traceback (most recent call last):
  File "/app/plexist/plexist.py", line 14, in <module>
    from modules.spotify import spotify_playlist_sync
  File "/app/plexist/modules/spotify.py", line 43
    title = track["track"]["name"]
    ^

**Comment by Gyarbij** [comment]
Can you try the 'test' tag? I'll really have to take a look with my Spotify account if it doesn't work after this. I typed this last night but forget to send

**Comment by Mikec78660** [comment]
The test container is working perfect! Thank you so much. This docker container has been the best addition to my plex server. Thank you so much for creating it.

**Comment by Gyarbij** [comment]
> The test container is working perfect! Thank you so much. This docker container has been the best addition to my plex server. Thank you so much for creating it.

No problem and thanks for catching it along with technikly.
